apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: monitor-hpa
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monitor-deploy
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
