apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-apache
  namespace: default
  labels:
    storage: nfs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteMany
  mountOptions:
  - hard
  - timeo=60
  - retrans=10
  capacity:
    storage: 1Gi
  nfs:
    path: /var/nfs/logs/apache2
    server: {{ .Values.nfs.privateip }}
  persistentVolumeReclaimPolicy: Retain
