apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-promt # The name of this Persistent Volume Claim
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # The size of the storage claim.
  storageClassName: ""
  selector:
    matchLabels:
      storage: "nfs"
  volumeName: pv-promt
