apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-config-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:AYaskuld/K8s_monitor.git'
    targetRevision: HEAD
    path: config_app
    helm:
      valueFiles:
        - values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
