apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hpa-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.githubssh.link }}
    targetRevision: HEAD
    path: hpa
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
