apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-pv-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.githubssh.link }}
    targetRevision: HEAD
    path: pv
    helm:
      valueFiles:
        - values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
