apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: windows-app
spec:
  syncWindows:
  - kind: allow
    schedule: '10 1 * * *'
    duration: 1h
    applications:
    - '*'
    manualSync: true
  - kind: deny
    schedule: '0 19 * * *'
    duration: 1h
    namespaces:
    - default
  - kind: allow
    schedule: '0 23 * * *'
    duration: 1h
    clusters:
    - https://kubernetes.default.svc
