apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-conf
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ["172.31.25.103:30909"]

      - job_name: 'node'
        static_configs:
        - targets: ["172.31.25.103:30910"]
