apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-conf
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  config.yml: |
        server:
          http_listen_port: 9080
          grpc_listen_port: 0

        positions:
          filename: /tmp/positions.yaml

        clients:
          - url: http://monitor-service:3100/loki/api/v1/push

        scrape_configs:
        - job_name: system
          static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/*log

        - job_name: nginx
          static_configs:
          - targets:
              - {{ .Values.workernode.privateip }}:30180
            labels:
              job: nginx
              __path__: /var/log/nginx/*log
              host: grafana

        - job_name: apache2
          static_configs:
          - targets:
              - {{ .Values.workernode.privateip }}:30188
            labels:
              job: apache2
              __path__: /var/log/apache2/*log
              host: grafana
