apiVersion : v1
kind: Service
metadata:
  name: monitor-service
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  type: NodePort
  selector:
    app: myapp
    project: monitor
  ports:
  - name: container-apache
    protocol: TCP
    port: 8080
    nodePort: 30188

  - name: container-nginx
    protocol: TCP
    port: 80
    nodePort: 30180

  - name: exporter-container
    protocol: TCP
    port: 9100
    nodePort: 30910

  - name: prometheus-container
    protocol: TCP
    port: 9090
    nodePort: 30909

  - name: container-loki
    protocol: TCP
    port: 3100
    nodePort: 30310

  - name: container-grafana
    protocol: TCP
    port: 3000
    nodePort: 30300
